CREATE TABLE MonitoringData (
	UIDATA UUID,
	DATETIME TIMESTAMP,
	VALUENUMCPU NUMERIC,
	CHECK (VALUENUMCPU >= 0 AND VALUENUMCPU <= 100),
	VALUENUMRAM NUMERIC,
	CHECK (VALUENUMRAM >= 0 AND VALUENUMRAM <= 100)
 );
 
