INSERT INTO monitoringdata (uidata, datetime, valuenumcpu, valuenumram) 
VALUES
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 28 , 89),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 80 , 29),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 50 , 50),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 12 , 34),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 45 , 15),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 89 , 34),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 67 , 59),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 20 , 80),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 28 , 89),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 60 , 53),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 93 , 31),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 70 , 39),
(GEN_RANDOM_UUID(),CURRENT_TIMESTAMP, 64 , 30)
